export const enum apis {
    //prouds
    check = "https://sp.ethci.org/check",
    login = "https://sp.ethci.org/perform_login",
    logout = 'https://sp.ethci.org/logout',
    newWorld = "https://sp.ethci.org/api/world/newWorld",
    getWorlds = 'https://sp.ethci.org/api/world/getOwnWorld',
    findByid = "https://sp.ethci.org/api/world/findByID?id=",
    delByID = "https://sp.ethci.org/api/world/delByID?id=",
    saveWorld = "https://sp.ethci.org/api/world/save",
    newLight = "https://sp.ethci.org/api/world/newLight",
    uploadModel = "https://sp.ethci.org/api/model/upload",
    newCollision = "https://sp.ethci.org/api/world/newCollision",
    newMaterial = "https://sp.ethci.org/api/world/newMaterial",
    newCompoent = "https://sp.ethci.org/api/DefaultComponent/upload",
    addCompoent = "https://sp.ethci.org/api/DefaultComponent/add",
    updateMaterial = "https://sp.ethci.org/api/world/updateMaterial",
    savePic = "https://sp.ethci.org/api/world/savePic",
    getPic = "https://meta.ethci.org/model/getPic/",
    getModel = "https://meta.ethci.org/model/getModel/",
    getMaterial = "https://meta.ethci.org/test/getMaterial/",
    getCompoentResource = "https://meta.ethci.org/test/getPicture/",
    register = "https://sp.ethci.org/api/user/register",
    tts = "https://meta.ethci.org/tts",
    setKey = "https://sp.ethci.org/api/user/setKey",
    getKey = "https://sp.ethci.org/api/user/getKey",
    getAccounts = "https://sp.ethci.org/api/user/findAll",
    getUserLogs = 'https://sp.ethci.org/api/user/getUserLog',
    getAllkey = "https://meta.ethci.org/test/getKey/",
    listLog = "https://meta.ethci.org/test/logs/",
    getLog = "https://meta.ethci.org/test/getLog/"

    //devs
    // check = "https://localhost:2087/check",
    // login = "https://localhost:2087/perform_login",
    // logout = 'https://localhost:2087/logout',
    // newWorld = "https://localhost:2087/api/world/newWorld" ,
    // getWorlds = 'https://localhost:2087/api/world/getOwnWorld',
    // findByid = "https://localhost:2087/api/world/findByID?id=",
    // delByID = "https://localhost:2087/api/world/delByID?id=",
    // saveWorld = "https://localhost:2087/api/world/save",
    // newLight = "https://localhost:2087/api/world/newLight",
    // uploadModel = "https://localhost:2087/api/model/upload",
    // newCollision = "https://localhost:2087/api/world/newCollision",
    // newMaterial = "https://localhost:2087/api/world/newMaterial",
    // newCompoent  = "https://localhost:2087/api/DefaultComponent/upload",
    // addCompoent = "https://localhost:2087/api/DefaultComponent/add",
    // updateMaterial = "https://localhost:2087/api/world/updateMaterial",
    // savePic = "https://localhost:2087/api/world/savePic",
    // getPic = "http://localhost:80/model/getPic/",
    // getModel = "http://localhost:80/model/getModel/",
    // getMaterial = "http://localhost:80/test/getMaterial/",
    // getCompoentResource = "http://localhost:80/test/getPicture/",
    // register = "http://localhost:80/api/user/register",
    // tts = "http://localhost:80/tts",
    // setKey = "https://localhost:2087/api/user/setKey",
    // getKey = "https://localhost:2087/api/user/getKey"
    // getAllkey = "http://localhost/test/getKey/",
    // listLog = "http://localhost/test/logs/",
    // getLog = "http://localhost/test/getLog/"
}